#!/bin/bash

# This script is used to convert the file names to the snakefile required JSON like format. 

# output example: 

# ["L01","L02","L03","L04","L05","L06","LT1","LT2","LT3","LT4","LT5","LT6","L01","L02","L03","L04","L05","L06","LT1","LT2","LT3","LT4","LT5","LT6"]

for i in *R1*.fastq.gz; do echo $(sed "s/_S1_R1_001.fastq.gz//" <(echo $i)) >> ./tmp; done
jq -Rc . ./tmp | jq -sc . 
rm ./tmp
